name: 'questdb-post'
description: 'Post data to questdb'
inputs:
  bin-name:
    description: 'The name of the binary being generated'
    type: string
    required: true
  size:
    description: 'Size of binary file in bytes'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "echo params"
      run: |
        echo "${{ inputs.bin-name }} ${{ inputs.size }}"

    - name: "Post data to questdb"
      id: post
      run: |
        curl -v -i -X POST \
        "http://questdb.zp-ads-monitoring.k3s-dev-poc.ra-digip.net:80/write" \
        --data-binary \
        "test_ingest,project_name=${{ inputs.bin-name }} size=${{ inputs.size }} $(date +%s)"
      shell: bash
