name: ingest-data
on:
  workflow_dispatch

jobs:
  Ingest-Data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'msargent-dev/prometheus-memory-spike'
          path: 'tmp'

      - name: Call Test Action
        run:
          ls tmp/.github

      - name: run python workflow
        uses: msargent-dev/prometheus-memory-spike/.github/actions/quest-db@main
        with:
          bin-name: 'test-bin'
          size: 10
      
