name: ingest-data
on:
  workflow_dispatch

jobs:
  Ingest-Data:
    runs-on: ubuntu-latest

    steps:
      - name: run python workflow
        uses: msargent-dev/prometheus-memory-spike/.github/actions/quest-db-text@main
        with:
          namespace: 'zt-ateam-sys-test-01'
          end-timestamp: '2024-04-23T17:25:59Z'
          length: '1h'
          repository-name: 'test-run-repo'
